### ISSUE TITLE
Brb Can you explain what is this list

### ISSUE THREAD

**Issue by ka0un** [LagKnowsWhy/begging-list#1]

**Comment by 0x796935** [comment]
???

**Comment by 0x796935** [comment]
List of usernames of people which begged for ranks in hypixel, it's pretty much outdated now

**Comment by ka0un** [comment]
Damn brb that’s crazy theres my name on it xD From: 0x796935Sent: Friday, January 26, 2024 5:43 AMTo: 0x796935/begging-listCc: kasun; AuthorSubject: Re: [0x796935/begging-list] Brb Can you explain what is this list (Issue #1) List of usernames of people which begged for ranks in hypixel, it's pretty much outdated now—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Redapple-one** [comment]
WTF 27697 lines
